love it

diff --git a/kindle-high b/kindle-high
--- a/kindle-high
+++ b/kindle-high
@@ -6,7 +6,7 @@ path=$(realpath "$0" | sed 's|\(.*\)/.*|\1|')
 cd $path
 
 if [ ! -z $1 ]; then 
-  [[ $1 == "fetch" ]] && python3 "fetch.py" || echo "invalid command: try 'fetch'"; exit 1;
+  [[ $1 == "fetch" ]] && python3 "fetch.py" || echo "invalid command: try 'kindle-high fetch'"; exit 1;
 fi
 
 # Calling prompt
